// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaC94qjicJCbUJFacCfqSXlD63y4qFcQ',
    appId: '1:144924319342:android:a487d8fbb6f4aaf5e8d07f',
    messagingSenderId: '144924319342',
    projectId: 'pettrail-74301',
    databaseURL: 'https://pettrail-74301-default-rtdb.firebaseio.com',
    storageBucket: 'pettrail-74301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEb1Ep2dmgvGfQDQ_gkJu6raCHKr7zafE',
    appId: '1:144924319342:ios:960d6207ae2c7d6ce8d07f',
    messagingSenderId: '144924319342',
    projectId: 'pettrail-74301',
    databaseURL: 'https://pettrail-74301-default-rtdb.firebaseio.com',
    storageBucket: 'pettrail-74301.firebasestorage.app',
    iosBundleId: 'com.pettrail.petTrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_gu0AA6EzI3CYJZyYnZBwTgB3mkCCghQ',
    appId: '1:144924319342:web:71214f9d0f2abae7e8d07f',
    messagingSenderId: '144924319342',
    projectId: 'pettrail-74301',
    authDomain: 'pettrail-74301.firebaseapp.com',
    databaseURL: 'https://pettrail-74301-default-rtdb.firebaseio.com',
    storageBucket: 'pettrail-74301.firebasestorage.app',
    measurementId: 'G-66YX1Y4SD2',
  );
}
